### ISSUE TITLE
Not starting on Mac OS 10

### ISSUE THREAD

**Issue by BKLronin** [BKLronin/underbridge-pro-doc#3]
Most likely missing downward compatibility as it is compiled on OS 11

/Applications/ubridge_mac/ubridge-pro ; exit;
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
File "[ubridge-pro.py](http://ubridge-pro.py/)", line 9, in <module>
File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
File "[pyaudio.py](http://pyaudio.py/)", line 116, in <module>
ImportError: dlopen(/var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/_portaudio.cpython-310-darwin.so, 2): Symbol not found: ____chkstk_darwin
Referenced from: /var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/libportaudio.2.dylib (which was built for Mac OS X 11.0)
Expected in: /usr/lib/libSystem.B.dylib
in /var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/libportaudio.2.dylib
[727] Failed to execute script 'ubridge-pro' due to unhandled exception: dlopen(/var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/_portaudio.cpython-310-darwin.so, 2): Symbol not found: ____chkstk_darwin
Referenced from: /var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/libportaudio.2.dylib (which was built for Mac OS X 11.0)
Expected in: /usr/lib/libSystem.B.dylib
in /var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/libportaudio.2.dylib
[727] Traceback:
Traceback (most recent call last):
File "[ubridge-pro.py](http://ubridge-pro.py/)", line 9, in <module>
File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
File "[pyaudio.py](http://pyaudio.py/)", line 116, in <module>
ImportError: dlopen(/var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/_portaudio.cpython-310-darwin.so, 2): Symbol not found: ____chkstk_darwin
Referenced from: /var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/libportaudio.2.dylib (which was built for Mac OS X 11.0)
Expected in: /usr/lib/libSystem.B.dylib
in /var/folders/6x/q73yj5rj5rs8s94lkzyq288w0000gn/T/_MEI8WYDyT/libportaudio.2.dylib

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...11 completed.

[Process completed]

**Comment by BKLronin** [comment]
The minimum required macOS is theoretically 10.15 as it is with pyinstaller.
